# 워크플로우의 이름
name: Daily Global Issue Report

on:
  # 수동으로 실행할 수 있도록 버튼을 추가합니다 (테스트용)
  workflow_dispatch:

  # 스케줄에 따라 실행
  schedule:
    # 매일 UTC 0시 (한국 시간 오전 9시)에 실행
    - cron: '0 0 * * *'

jobs:
  # 실행할 작업의 이름
  send-report:
    # 실행될 가상 환경 (최신 우분투)
    runs-on: ubuntu-latest

    # 작업 단계들
    steps:
    # 1. 저장소의 코드를 가상 환경으로 가져오기
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Python 3.10 설치
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. 필요한 라이브러리 설치 (requirements.txt 기반)
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    # 4. 파이썬 스크립트 실행
    - name: Run Python script to send report
      # GitHub Secrets에 저장한 Webhook URL을 스크립트에 전달
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python send_report.py
